spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true
      ddl-auto: create


jwt:
  expiration: 36000000
  secret: SECRETO