# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file cabal-neo-admin/pom.xml

      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          username: ${{  secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Criando a Imagem Docker
        uses: docker/build-push-action@v2.3.0
        with:
          tags: |
            jeanlucafp/cabalneobackend:latest
            jeanlucafp/cabalneobackend:${{ github.run_number }}
          push: true
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Definindo o contexto do Kubernetes
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - name: Deploy API
        uses: Azure/k8s-deploy@v1.3
        with:
          images: 'jeanlucafp/cabalneobackend:${{ github.run_number }}'
          manifests: |
            cabal-neo-admin/k8s/deployment.yaml
            cabal-neo-admin/k8s/service.yaml        
